services:
  backend:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    container_name: articles-server
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - shared-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: postgres-server
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

networks:
  shared-network:

volumes:
  pg_data: