services:
  backend:
    build: ./
    container_name: articles-server
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - shared-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres-server
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

networks:
  shared-network:

volumes:
  pg_data: