application:
  env: "dev"

http_server:
  address: "0.0.0.0"
  public_port: 8080
  private_port: 8081
  timeout: 4s
  idle_timeout: 60s

database:
  host: "postgres"
  port: 5432
  name: "articles"
  user: "postgres"
  password: "secret_password"