application:
  env: "local" # local, dev, prod

http_server:
  address: "0.0.0.0"
  port: 8080
  timeout: 4s
  idle_timeout: 60s

database:
  host: "postgres" # service name from docker compose
  port: 5432
  name: "articles"
  user: "postgres"
  password: "secret_password"